### ISSUE TITLE
Crashes on Utlimaker 4.0.0

### ISSUE THREAD

**Issue by hughesjs** [BluefireXD/Anycubic-Chiron-Cura-Definitions-incl.-printer-profiles#1]
Upon creating new printer definition, the following crash occurs.

Trace:

> Traceback (most recent call last):
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\cura\Settings\MachineManager.py", line 398, in addMachine
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\cura\Settings\CuraStackBuilder.py", line 68, in createMachine
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\cura\Settings\CuraStackBuilder.py", line 128, in createExtruderStackWithDefaultSetup
> IndexError: list index out of range
> 

Logs:

> Thread 0x00000ffc (most recent call first):
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\Backend\Backend.py", line 169 in _storeStderrToLogThread
>   File "threading.py", line 862 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00001a44 (most recent call first):
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\Backend\Backend.py", line 161 in _storeOutputToLogThread
>   File "threading.py", line 862 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00002224 (most recent call first):
>   File "C:\Program Files\Ultimaker Cura 4.0\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 78 in _updateThread
>   File "threading.py", line 862 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x000003f8 (most recent call first):
>   File "threading.py", line 297 in wait
>   File "zeroconf.py", line 1569 in wait
>   File "zeroconf.py", line 1153 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00000aa4 (most recent call first):
>   File "threading.py", line 297 in wait
>   File "zeroconf.py", line 1569 in wait
>   File "zeroconf.py", line 1017 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00002cd0 (most recent call first):
>   File "zeroconf.py", line 946 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00001480 (most recent call first):
>   File "threading.py", line 297 in wait
>   File "threading.py", line 549 in wait
>   File "C:\Program Files\Ultimaker Cura 4.0\plugins\UM3NetworkPrinting\src\UM3OutputDevicePlugin.py", line 344 in _handleOnServiceChangedRequests
>   File "threading.py", line 862 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x000003fc (most recent call first):
>   File "C:\Program Files\Ultimaker Cura 4.0\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
>   File "threading.py", line 862 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x0000052c (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x000020d4 (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00000bc4 (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00001588 (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00001210 (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00000270 (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00000f84 (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00000bf8 (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x000027b4 (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00002144 (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00001970 (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Thread 0x00000940 (most recent call first):
>   File "threading.py", line 293 in wait
>   File "threading.py", line 424 in acquire
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 86 in _nextJob
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\JobQueue.py", line 112 in run
>   File "threading.py", line 914 in _bootstrap_inner
>   File "threading.py", line 882 in _bootstrap
> 
> Current thread 0x0000022c (most recent call first):
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 306 in _logInfoWidget
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 156 in _createDialog
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\cura\CrashHandler.py", line 77 in __init__
>   File "X:\4.0\build\inst\bin\cura_app.py", line 98 in exceptHook
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\UM\Qt\QtApplication.py", line 324 in exec_
>   File "X:\4.0\build\inst\lib\python3.5\site-packages\cura\CuraApplication.py", line 761 in run
>   File "X:\4.0\build\inst\bin\cura_app.py", line 132 in <module>
>   File "Console.py", line 24 in <module>
>   File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
>   File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 969 in _find_and_load
>   File "__startup__.py", line 12 in <module>
>   File "<frozen importlib._bootstrap>", line 634 in _load_backward_compatible
>   File "<frozen importlib._bootstrap>", line 664 in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 958 in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 969 in _find_and_load

**Comment by PatrickGlatt** [comment]
Thx for the report. 
On the first look i can't see a chiron def file in the logs. 
I will take a look on it and test it again.
